services:
  redis:
    image: redis:7.2
    container_name: redis_aiwaiter
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /Users/taherpanbiharwala/Desktop/Win/Flow/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10